# SPDX-FileCopyrightText: 2022 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: Apache-2.0 OR BSD-3-Clause

[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools",
    "setuptools-scm",
    "build",
    "wheel",  # @ git+https://github.com/pypa/wheel.git@main
    "ctypesgen @ git+https://github.com/ctypesgen/ctypesgen.git@master",
]
