# SPDX-FileCopyrightText: 2023 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: CC-BY-4.0

name: Other issue
description: Generic issue template

body:
  - type: textarea
    attributes:
      label: Description
      description: Please explain your problem
