# SPDX-FileCopyrightText: 2023 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: Apache-2.0 OR BSD-3-Clause

# Separate trigger workflow because we can't configure inputs for scheduled workflow runs (and don't want publish enabled by default in the main workflow)

name: Trigger Release
on:
  # https://github.com/bblanchon/pdfium-binaries/blob/master/.github/workflows/trigger.yml
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  # https://crontab.guru/
  schedule:
    - cron: '0 4 10 * *'  # new monthly schedule
    # - cron: '0 4 * * 2'   # old weekly schedule
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger Release
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build_packages.yaml
          inputs: |
            {
              "pre_test": "false",
              "test": "true",
              "publish": "true",
              "py_version": "3.10",
              "runner": "ubuntu-latest"
            }
